[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "example_package"
version = "0.0.1"
dependencies = ["numpy"]

[project.optional-dependencies]
test = ["pytest"]
