[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "example_package"
version = "0.0.1"
requires-python = ">=3.8"
dependencies = [
  "numpy>=1.13.3",
]
[project.optional-dependencies]
test = [
  "pytest >=7.0",
]
